import type { PluginDescriptor, PluginSkill } from "@ericsanchezok/synergy-plugin"
import { setupCommand } from "./setup"

// === SKILLS: generated by scripts/sync-descriptions.ts; do not edit manually ===
export const SKILL_ENTRIES: PluginSkill[] = [
  {
    name: "project-init",
    description:
      "Teaches the agent to self-diagnose and auto-initialize frontend tooling before starting design work. Use when starting a new frontend project or when MCP tools return errors indicating missing configuration. Triggers: 'new project', 'init', 'setup', 'MCP error', 'tool not available'.",
    dir: "skills/project-init",
  },
  {
    name: "frontend-design",
    description:
      "Guidance for distinctive, intentional visual design when building new UI or reshaping an existing one. Helps with aesthetic direction, typography, and making choices that don't read as templated defaults.",
    dir: "skills/frontend-design",
  },
  {
    name: "taste-frontend",
    description:
      "Anti-slop frontend skill for landing pages, portfolios, and redesigns. The agent reads the brief, infers the right design direction, and ships interfaces that do not look templated. Real design systems when applicable, audit-first on redesigns, strict pre-flight check.",
    dir: "skills/taste-frontend",
  },
  {
    name: "color-expert",
    description:
      "Use when working with color naming, color theory, color spaces, color definitions, or any task involving color knowledge - palettes, ramps, gradients, conversions, accessibility, perceptual matching, pigment mixing, print-vs-screen color, CSS color syntax, or historical color terminology. Use this skill whenever the user is choosing, comparing, generating, naming, converting, or explaining colors, even if they do not explicitly ask for \"color theory.\"",
    dir: "skills/color-expert",
  },
  {
    name: "typography",
    description:
      "Apply professional typography principles to create readable, hierarchical, and aesthetically refined interfaces. Use when setting type scales, choosing fonts, adjusting spacing, designing text-heavy layouts, implementing dark mode typography, or when asked about readability, font pairing, line height, measure, typographic hierarchy, variable fonts, font loading, or OpenType features.",
    dir: "skills/typography",
  },
  {
    name: "motion-design",
    description:
      "Applies motion design principles to create emotionally-driven, technically sound animations and transitions. Provides timing, easing, choreography, and Disney animation principles adapted for UI. Use when creating animations, transitions, micro-interactions, loading states, page transitions, scroll-triggered effects, or any motion work. Works with CSS, Framer Motion, GSAP, Lottie, Spring, or any animation system.",
    dir: "skills/motion-design",
  },
  {
    name: "implementation-rules",
    description:
      "Deterministic coding rules to prevent AI-generated frontend anti-patterns. Covers color palettes, typography, layout structure, spacing, motion, and accessibility — 24 concrete DO/DON'T rules. Use when writing any frontend code — these are standing orders, not situational guidance. Triggers: 'CSS', 'style', 'component', 'layout', 'Tailwind', 'animation', 'font', 'color', 'spacing', 'accessibility'.",
    dir: "skills/implementation-rules",
  },
  {
    name: "a11y-audit",
    description:
      "Run accessibility audits on web projects combining automated scanning (axe-core, Lighthouse) with WCAG 2.1 AA compliance mapping, manual check guidance, and structured reporting. Output is configurable: markdown report only, markdown plus machine-readable JSON, or markdown plus issue tracker integration. Use this skill whenever the user mentions \"accessibility audit\", \"a11y audit\", \"WCAG audit\", \"accessibility check\", \"compliance scan\", or asks to check a web project for accessibility issues. Also trigger when the user wants to verify WCAG conformance or map findings to a specific standard (CAN-ASC-6.2, EN 301 549, ADA/AODA).",
    dir: "skills/a11y-audit",
  },
  {
    name: "soft-design",
    description:
      "Teaches the AI to design like a high-end agency. Defines the exact fonts, spacing, shadows, card structures, and animations that make a website feel expensive. Blocks all the common defaults that make AI designs look cheap or generic.",
    dir: "skills/soft-design",
  },
  {
    name: "minimalist-design",
    description:
      "Clean editorial-style interfaces. Warm monochrome palette, typographic contrast, flat bento grids, muted pastels. No gradients, no heavy shadows.",
    dir: "skills/minimalist-design",
  },
]
// === END SKILLS ===

export const FrontendKitPlugin: PluginDescriptor = {
  id: "synergy-frontend-kit",
  name: "Synergy Frontend Kit",

  async init(ctx) {
    return {
      skills: SKILL_ENTRIES,
      cli: {
        setup: setupCommand(ctx),
      },
    }
  },
}

export default FrontendKitPlugin
